# Site settings
title: site title
email: your-email@domain.com
description: "site description"
encoding: utf-8
baseurl: "/"
url: "http://sarhov.github.io/akumlyator"

# Build settings
markdown: rdiscount
permalink: pretty