# Site settings
title: site title
email: your-email@domain.com
description: "site description"
baseurl: "http://sarhov.com/akumlyator/"
url: "/"

# Build settings
markdown: rdiscount
permalink: pretty